### PR TITLE
41 - Create Database Models - Baz

### LINKED ISSUE #41: Create Database Entity/Model for News, Events and Services
(@bazmurphy edit:)

We need to define the Models (Schemas / Entities) for the API

The dynamic content so far is : 
- News
- Events 
- Services

Useful Documentation: 
https://docs.strapi.io/dev-docs/backend-customization/models

Attempt at defining the Models:

- **News**
  - **id**: (automatically created) - [Number] Do we need uuid as string(?)
  - **updatedAt**: (automatically created)
  - **createdAt**: (automatically created)
  - **title** - the title of the News Article [REQUIRED]
  - **date**(?) - the date of the News Article [REQUIRED]
  - **type/category**(?) [Enum] - the category of the news article eg.  [perhaps unnecessary] [REQUIRED]
    - [ Mental health & wellness, Beehive activities, Garden Project, Patient Stories, Child & Adolescent ward renovation]
  - **summary**(?) - a short description of the news article used in smaller cards [REQUIRED]
  - **description** - a full description of the News article's main body of text used in a full card (or modal?) [REQUIRED]
  - **images** - a main image (and maybe a set of subsequent images for the News Article) [REQUIRED]
  - [**author** - the author of the News article]
  - **slug**(?)

- **Events**
  - **id**: (automatically created) - [Number] Do we need uuid as string(?)
  - **updatedAt**: (automatically created)
  - **createdAt**: (automatically created)
  - **title** - the title of the Event [REQUIRED]
  - **startDate** - the date the Event is starting [REQUIRED]
  - **endDate** - the date the Event is ending [REQUIRED]
  - **startTime** - the start time of the Event [REQUIRED]
  - **endTime** - the end time of the Event [REQUIRED]
  - **location** - the location of the Event [REQUIRED]
  - **type/category**(?) - the type of the Event [REQUIRED] +1 Option Other
  - **summary**(?) - a short description of the Event used in smaller cards [REQUIRED] 300
  - **description** - a full description of the Event used in a full page [REQUIRED]
  - **images** - a main image (and maybe a set of subsequent images for the Event)
  - **slug**(?) (for dynamic routing)
  - [**author** - the author of the Event]

- **Services** [ ASK for Structure ]
  - **id**: (automatically created) - [Number] Do we need uuid as string(?)
  - **updatedAt**: (automatically created)
  - **createdAt**: (automatically created)
  - **title** - the title of the Service [REQUIRED]
  - **summary**(?) - a short description of the Service used in smaller cards [REQUIRED]
  - **description** - a full description of the Service used in a full page [REQUIRED]
  - **images** - a main image (and maybe a set of subsequent images for the Service) [REQUIRED]
  - **openingHours**(?) - the opening hours for the Service
  - **contactDetails**(?) - the contact details for the Service
  - **slug**(?) (for dynamic routing) [generate]

### PR DESCRIPTION
**Pull request by bazmurphy**
## Description

This PR defines the data structures for the following database model/schemas:

- **News Article**
  - `title` - the title of the news article (required) [unique] [min length 3]
  - `slug` - the slugified version of the title eg. "some-news-title" (required) [min length 3]
  - `date` - the date of the news article (required)
  - `category` - the category of the news article - a single option from many (required)
  - `tags` - the tags associated with the news article - multiple options from many (optional)
  - `summary` - a short summary of the news article (required) (text field) [min length 3 & max length 200]
  - `content` - the main content of the news article (required) (rich text field editor)
  - `images` - the images for the news article (required) (image media upload)

- News Article **Query Examples**:
  - `/api/news-article`
  - `/api/news-article?populate=*`
  - `/api/news-article/1`
  - `/api/news-article/1?populate=*`

---

- **Event** `/api/event`
  - `title` - the title of the news article (required) [unique] [min length 3]
  - `slug` - the slugified version of the title eg. "some-event-title" (required) [min length 3]
  - `startDate` - the start date of the event (required)
  - `endDate` - the end date of the event (optional)
  - `startTime` - the start time of the event (required)
  - `endTime` - the end time of the event (optional)
  - `location` - the location of the event (required)
  - `category` - the category of the event - a single option from many (required)
  - `tags` - the tags associated with the event - multiple options from many (optional)
  - `summary` - a short summary of the event (required) (text field) [min length 3 & max length 200]
  - `content` - the main description of the event (required) (rich text field editor)
  - `images` - the images for the event (required) (image media upload)

- Event **Query Examples**:
  - `/api/event`
  - `/api/event?populate=*`
  - `/api/event/1`
  - `/api/event/1?populate=*`

---

- **Service** `/api/service`
  - `title` - the title of the service (required) [unique] [min length 3]
  - `slug` - the slugified version of the title eg. "some-service-title" (required) [min length 3]
  - `category` - the category of the service - a single option from many (required)
  - `tags` - the tags associated with the service - multiple options from many (optional)
  - `summary` - a short summary of the service (required) (text field) [min length 3 & max length 200]
  - `content` - the main description of the service (required) (rich text field editor)
  - `images` - the images for the service (required) (image media upload)

- Service**Query Examples**:
  - `/api/service`
  - `/api/service?populate=*`
  - `/api/service/1`
  - `/api/service/1?populate=*`

---

- **Gallery Album** `/api/gallery-album`
  - `title` - the title of the gallery album (required) [unique] [min length 3]
  - `slug` - the slugified version of the title eg. "some-service-title" (required) [min length 3]
  - `category` - the category of the gallery album - a single option from many (required)
  - `tags` - the tags associated with the gallery album - multiple options from many (optional)
  - `summary` - a short summary of the gallery album (required) (text field) [min length 3 & max length 200]
  - `images` - the images of the album (required) (image media upload)

- Gallery **Query Examples**:
  - `/api/gallery-album`
  - `/api/gallery-album?populate=*`
  - `/api/gallery-album/1`
  - `/api/gallery-album/1?populate=*`

---
   
## Related to

Fixes #41 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have carefully reviewed my own code
- [X] ~I have commented my code~
- [X] I have updated any documentation

### CODE REVIEW

**Review by ShayanMahnam — APPROVED** [review]
well done!
- I test it and everything is working 
- what do you think about categories? we have it everywhere should we create a different table for it and make it related to other tables?
just a suggestion we can do it in another PR or Talk about it later 
- For the **MVP** category should be enough **Tags** too much I think 

Screenshot 2023-07-07 at 11 31 27

**Comment by KhadijaHaji** [comment]
Used postman to make GET requests, it's working! Great job Screenshot 2023-07-07 at 13 44 17

**Comment by KhadijaHaji** [comment]
I can see you re-configured the content type to follow the order we wanted. I was just confused as to why the images are always last even though the images usually go before the title etc Screenshot 2023-07-07 at 13 45 53
Screenshot 2023-07-07 at 13 46 11

**Review by KhadijaHaji — COMMENTED** [review]
Great work!

**Pull request merged**
